## AX6 — sysupgrade 保留配置文件
## /etc/config/ 默认已保留，此处添加额外路径

# ZeroTier 身份密钥 (删除 = 新地址!)
/etc/zerotier/

# OpenClash 配置
/etc/openclash/config/

# 定时任务
/etc/crontabs/

# DDNS
/etc/ddns-go/

# Dropbear SSH 密钥
/etc/dropbear/

# uHTTPd SSL
/etc/uhttpd.crt
/etc/uhttpd.key
