#!/bin/sh /etc/rc.common

# shellcheck disable=SC2034 # Read by /etc/rc.common.
START=91
# shellcheck disable=SC2034 # Read by /etc/rc.common.
STOP=10
# shellcheck disable=SC2034 # Read by /etc/rc.common.
USE_PROCD=1
PROG=/usr/sbin/ax6-zerotier-reconcile

start_service() {
	[ -x "$PROG" ] || return 1
	procd_open_instance
	procd_set_param command "$PROG" --daemon
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 0
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	"$PROG" --once
}

service_triggers() {
	procd_add_reload_trigger zerotier openclash firewall
}
