#!/bin/sh
# AX6 国内友好默认值:NTP + DNS(只在首次启动跑)
# 用户可在 /etc/config/system 与 /etc/config/dhcp 中后续修改

# ===========================================================
# NTP:阿里 + 国家授时中心 + 腾讯
# ===========================================================
uci -q delete system.ntp.server
uci -q add_list system.ntp.server='ntp.aliyun.com'
uci -q add_list system.ntp.server='ntp.tencent.com'
uci -q add_list system.ntp.server='ntp.ntsc.ac.cn'
uci -q add_list system.ntp.server='cn.pool.ntp.org'
uci -q set system.ntp.enabled='1'
uci -q set system.ntp.enable_server='0'

# 时区
uci -q set system.@system[0].timezone='CST-8'
uci -q set system.@system[0].zonename='Asia/Shanghai'

uci -q commit system

# ===========================================================
# DNS 上游:阿里 + 腾讯 + DNSPod (over UDP/53,无加密)
# 用户如需 DoH/DoT 自行装 dnsmasq-full / smartdns
# ===========================================================
uci -q delete dhcp.@dnsmasq[0].server 2>/dev/null
uci -q add_list dhcp.@dnsmasq[0].server='223.5.5.5'
uci -q add_list dhcp.@dnsmasq[0].server='119.29.29.29'
uci -q add_list dhcp.@dnsmasq[0].server='114.114.114.114'

# 不要 ISP DNS 污染
uci -q set dhcp.@dnsmasq[0].noresolv='1'
uci -q set dhcp.@dnsmasq[0].rebind_protection='1'
uci -q set dhcp.@dnsmasq[0].rebind_localhost='1'
uci -q set dhcp.@dnsmasq[0].localise_queries='1'
uci -q set dhcp.@dnsmasq[0].domainneeded='1'
uci -q set dhcp.@dnsmasq[0].cachesize='2000'

uci -q commit dhcp

exit 0
